import "@/assets/css/globals.css";
import "@/assets/css/reset.css";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import RootProvider from "./_common/RootProvider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootProvider>{children}</RootProvider>
        <div id="modal"></div>
        <div id="loading"></div>
      </body>
    </html>
  );
}
